#!/bin/sh

export WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
export XDG_RUNTIME_DIR=/run/weston/xdg_runtime

URL=${WPE_URL:-https://wpewebkit.org}
CPU_SCALING_GOVERNOR=${CPU_SCALING_GOVERNOR:-performance}

for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor)
do
    echo "${CPU_SCALING_GOVERNOR}" > $i
done

udevd &
udevadm trigger

# /var/tmp points to /var/volatile/tmp  what it doesn't exist
# /var/tmp is need for gstreamer to download chunks of videos
mkdir -p /var/volatile/tmp  || rm -rf /var/volatile/tmp/*

# Wait for the Wayland compositor is available
while ! /usr/bin/waylandeglinfo; do sleep 0.5; done

# Launch a D-Bus daemon for cogctl
mkdir -p /run/dbus/
dbus-launch > /run/dbus/env
export $(cat /run/dbus/env)

# Start browser
cog-fdo ${URL}

# Start Tohora
./tohora 8080 "cog-open"

