.export-prod:
  extends:
    - .prod
  stage: export-prod
  image: igalia/balena-cli-builder:aarch64
  tags:
    - docker-aarch64
  variables:
    MACHINE: raspberrypi3
    REGISTRY: $DOCKER_HUB_REGISTRY
    REGISTRY_USER: $DOCKER_HUB_USER
    REGISTRY_PASSWORD: $DOCKER_HUB_PASSWORD
    REGISTRY_PATH: igalia
  script:
    - bash ./push.sh

export-prod-balena-wpe-raspberrypi3:
  image: igalia/balena-cli-builder:arm32v7
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi3
    ARCH: armv7hf
  dependencies:
    - build-balena-wpe-raspberrypi3
  needs: ["build-balena-wpe-raspberrypi3"]

export-prod-balena-wpe-raspberrypi3-64:
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi3-64
  dependencies:
    - build-balena-wpe-raspberrypi3-64
  needs: ["build-balena-wpe-raspberrypi3-64"]

export-prod-balena-wpe-raspberrypi4:
  image: igalia/balena-cli-builder:arm32v7
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi4
    ARCH: armv7hf
  dependencies:
    - build-balena-wpe-raspberrypi4
  needs: ["build-balena-wpe-raspberrypi4"]

export-prod-balena-wpe-raspberrypi4-64:
  extends:
    - .export-prod
  variables:
    MACHINE: raspberrypi4-64
  dependencies:
    - build-balena-wpe-raspberrypi4-64
  needs: ["build-balena-wpe-raspberrypi4-64"]

