.export-ci:
  stage: export-ci
  image: igalia/balena-cli-builder:aarch64
  tags:
    - docker-aarch64
  variables:
    MACHINE: raspberrypi3
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: gitlab-ci-token
    REGISTRY_PASSWORD: $CI_JOB_TOKEN
    REGISTRY_PATH: $CI_PROJECT_PATH
  script:
    - bash ./push.sh

export-ci-balena-wpe-raspberrypi3:
  image: igalia/balena-cli-builder:arm32v7
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi3
    ARCH: armv7hf
  dependencies:
    - build-balena-wpe-raspberrypi3
  needs: ["build-balena-wpe-raspberrypi3"]

export-ci-balena-wpe-raspberrypi3-64:
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi3-64
  dependencies:
    - build-balena-wpe-raspberrypi3-64
  needs: ["build-balena-wpe-raspberrypi3-64"]

export-ci-balena-wpe-raspberrypi4:
  image: igalia/balena-cli-builder:arm32v7
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi4
    ARCH: armv7hf
  dependencies:
    - build-balena-wpe-raspberrypi4
  needs: ["build-balena-wpe-raspberrypi4"]

export-ci-balena-wpe-raspberrypi4-64:
  extends:
    - .export-ci
  variables:
    MACHINE: raspberrypi4-64
  dependencies:
    - build-balena-wpe-raspberrypi4-64
  needs: ["build-balena-wpe-raspberrypi4-64"]

